name: 'Pull Request Checker'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '[a-zA-Z]+\-[0-9]+\ +.+.'
          flags: 'g'
          error: 'The commit title should include a jira tag. (eg."[TAG-1234 Sample commit]").'
  
  task-completed-check:
    name: Tasks Completed
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          
  pull-request-title:
    runs-on: ubuntu-latest
    steps:
    - uses: seferov/pr-lint-action@master
      with:
        title-regex: '[a-zA-Z]+\-[0-9]+\ +.+.'
        title-regex-flags: 'g'
