name: 'Pull Request Checker'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
jobs:
  jira-tag-checker:
    name: Jira Tag Checker
    runs-on: ubuntu-latest
    steps:
      - name: Check Jira Tag
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '[a-zA-Z]+\-[0-9]+\ +.+.'
          flags: 'g'
          error: 'The commit title should include a jira tag. (eg."[TAG-1234 Sample commit]").'
          
  pull-request-title:
    name: Pull Request Title
    runs-on: ubuntu-latest
    steps:
      - name: Check Pull Request Title
        uses: seferov/pr-lint-action@master
        with:
          title-regex: '[a-zA-Z]+\-[0-9]+\ +.+.'
          title-regex-flags: 'g'
  
  tasks-completed:
    name: Tasks Completed
    runs-on: ubuntu-latest
    steps:
      - name: Check Tasks Complete
        uses: kentaro-m/task-completed-checker-action@v0.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
  
  branch-name-rules:
    name: Branch Prefix Rules
    runs-on: [ubuntu-latest]
    steps:
      - name: Check Branch Prefix
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '[a-z]+\/[a-zA-Z]+-[0-9]+.+' # Regex the branch should match. This example enforces grouping
          allowed_prefixes: 'feature,bugfix' # All branches should start with the given prefix
          ignore: master
